/** @type {import('tailwindcss').Config} */
const withOpacity = (variableName) => `rgb(from var(${variableName}) r g b / <alpha-value>)`

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        white: withOpacity('--color-surface'),
        black: withOpacity('--color-inverse'),
        slate: {
          50: withOpacity('--color-surface-muted'),
          100: withOpacity('--color-border'),
          200: withOpacity('--color-border'),
          300: withOpacity('--color-border-strong'),
          400: withOpacity('--color-text-faint'),
          500: withOpacity('--color-text-muted'),
          600: withOpacity('--color-text-muted'),
          700: withOpacity('--color-text'),
          800: withOpacity('--color-text-strong'),
          900: withOpacity('--color-text-strong'),
          950: withOpacity('--color-inverse'),
        },
        sky: {
          50: withOpacity('--color-primary-soft'),
          100: withOpacity('--color-primary-soft'),
          200: withOpacity('--color-primary-border'),
          300: withOpacity('--color-primary-border'),
          400: withOpacity('--color-primary'),
          600: withOpacity('--color-primary'),
          700: withOpacity('--color-primary-strong'),
          800: withOpacity('--color-primary-strong'),
          900: withOpacity('--color-primary-strong'),
        },
        emerald: {
          50: withOpacity('--color-success-soft'),
          100: withOpacity('--color-success-soft'),
          200: withOpacity('--color-success-border'),
          500: withOpacity('--color-success'),
          600: withOpacity('--color-success'),
          700: withOpacity('--color-success-text'),
          800: withOpacity('--color-success-text'),
          900: withOpacity('--color-success-text'),
        },
        amber: {
          50: withOpacity('--color-warning-soft'),
          100: withOpacity('--color-warning-soft'),
          200: withOpacity('--color-warning-border'),
          400: withOpacity('--color-warning'),
          500: withOpacity('--color-warning'),
          700: withOpacity('--color-warning-text'),
          900: withOpacity('--color-warning-text'),
          950: withOpacity('--color-warning-text'),
        },
        rose: {
          50: withOpacity('--color-danger-soft'),
          100: withOpacity('--color-danger-soft'),
          200: withOpacity('--color-danger-border'),
          600: withOpacity('--color-danger'),
          700: withOpacity('--color-danger-text'),
          800: withOpacity('--color-danger-text'),
          900: withOpacity('--color-danger-text'),
        },
      },
      fontSize: {
        tiny: ['var(--font-size-tiny)', { lineHeight: 'var(--line-height-tight)' }],
        caption: ['var(--font-size-caption)', { lineHeight: 'var(--line-height-tight)' }],
        xs: ['var(--font-size-xs)', { lineHeight: 'var(--line-height-tight)' }],
        sm: ['var(--font-size-sm)', { lineHeight: 'var(--line-height-normal)' }],
        base: ['var(--font-size-base)', { lineHeight: 'var(--line-height-normal)' }],
        lg: ['var(--font-size-lg)', { lineHeight: 'var(--line-height-tight)' }],
        xl: ['var(--font-size-xl)', { lineHeight: 'var(--line-height-tight)' }],
        '2xl': ['var(--font-size-2xl)', { lineHeight: 'var(--line-height-tight)' }],
        '3xl': ['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
        '4xl': ['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
        '5xl': ['var(--font-size-5xl)', { lineHeight: 'var(--line-height-tight)' }],
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius-control)',
      },
    },
  },
  plugins: [],
}
