services:
  farm-atlas:
    image: ghcr.io/sitscholl/farmatlas:latest
    # ports:
    #   - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./db:/app/db
    restart: unless-stopped
    container_name: farm-atlas
